#!/bin/sh

CMDDESC="Generate GitBook"

#./node_modules/.bin/gitbook build ./txt ./gh-pages
#gitbook build `pwd` ./gh-pages

ssh usuario@10.6.128.159 'cd /home/usuario/Sytw/Styw3;git pull'

#scp -r ../. usuarior@10.6.128.159:/practica-heroku-iaas 